services:
  nginx:
    image: nginx:1.28
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/www:/usr/share/nginx/www
    ports:
      - "80:80"
      - "443:443"
    networks:
      - infra_net
  postgres:
    image: postgres:18.1
    container_name: postgres
    restart: unless-stopped
    networks:
      - infra_net
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Shanghai
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  redis:
    image: redis:7.4
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis:/data
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD}
    networks:
      - infra_net

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: dragz:latest
    container_name: dragz
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - ./local:/app/local
    ports:
      - "5280:5280"
    networks:
      - infra_net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres:
  redis:

networks:
  infra_net:
    external: true # use existing network

# docker-compose -p dragz up -d
