// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/tianjinli/dragz/internal/app/middleware"
	"github.com/tianjinli/dragz/internal/bootstrap/config"
	"github.com/tianjinli/dragz/internal/bootstrap/database"
	"github.com/tianjinli/dragz/internal/bootstrap/logger"
	"github.com/tianjinli/dragz/internal/bootstrap/redis"
	"github.com/tianjinli/dragz/internal/infra/engine"
	"github.com/tianjinli/dragz/internal/infra/jwtauth"
	"github.com/tianjinli/dragz/internal/infra/qrcode"
	"github.com/tianjinli/dragz/internal/infra/translate"
	"github.com/tianjinli/dragz/pkg/appkit"
)

// Injectors from wire.go:

func InitContainer() (*appkit.Container, func(), error) {
	bootstrap, cleanup, err := config.NewBootstrapConfig()
	if err != nil {
		return nil, nil, err
	}
	loggerConfig := bootstrap.Logger
	zapLogger, cleanup2, err := logger.NewLogger(loggerConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	databaseConfig := bootstrap.Database
	db, cleanup3, err := database.NewGormDB(databaseConfig, zapLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	redisConfig := bootstrap.Redis
	universalClient, cleanup4, err := redis.NewRedis(redisConfig, zapLogger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	qrcodeService := qrcode.NewQrcodeService(zapLogger)
	serverConfig := bootstrap.Server
	tokenConfig := bootstrap.Token
	jwtAuthService := jwtauth.NewJwtAuthService(zapLogger, universalClient, tokenConfig)
	i18nAdapter, err := translate.NewI18nAdapter(serverConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jwtAuthMiddleware := &middleware.JwtAuthMiddleware{
		JwtAuth:    jwtAuthService,
		Translator: i18nAdapter,
	}
	engineService, cleanup5, err := engine.NewEngineService(zapLogger, serverConfig, tokenConfig, jwtAuthMiddleware)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	container := &appkit.Container{
		Logger:    zapLogger,
		Database:  db,
		Redis:     universalClient,
		Config:    bootstrap,
		Qrcode:    qrcodeService,
		Engine:    engineService,
		JwtAuth:   jwtAuthService,
		Translate: i18nAdapter,
	}
	return container, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
