apiVersion: v1
kind: Secret
metadata:
  namespace: dragz
  name: postgres-secrets
stringData:
  POSTGRES_PASSWORD: "3NRK6wUGggWJtYzswUu1" # <<< replace me
  DB_MASTER_USER: "dragz" # <<< replace me
  DB_MASTER_DBNAME: "dragz" # <<< replace me
  DB_MASTER_PASSWORD: "M65wdffQJwm5hzZVE7q2" # <<< replace me
---
apiVersion: v1
kind: Secret
metadata:
  namespace: dragz
  name: redis-secrets
stringData:
  REDIS_PASSWORD: "qIvBK5e5V6jsKaQrmLIO" # <<< replace me
---
apiVersion: v1
kind: Secret
metadata:
  namespace: dragz
  name: server-certs
data:
  app-ca.crt: ""
---
